name: Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check SSH key exists
        run: |
          if [ -z "${{ secrets.VPS_SSH_KEY }}" ]; then
            echo "SSH key is EMPTY"
            exit 1
          else
            echo "SSH key is present"
          fi

      - name: Debug SSH key fingerprint
        run: |
          echo "${{ secrets.VPS_SSH_KEY }}" > /tmp/key
          chmod 600 /tmp/key
          ssh-keygen -lf /tmp/key

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/BE-Nest
            git fetch origin
            git checkout staging
            git pull origin staging
            docker compose down
            docker compose build
            docker compose up -d
